### ISSUE TITLE
Construct Overview page with components

### ISSUE THREAD

**Issue by scdorr86** [NSS-Evening-E22/gitsub-hex-clan-e22#14]
# User Story
Includes a form that allows a user to add a pinned repository
STRETCH GOALS:
Allow users to Delete Pins
Create the About area shown in the Wireframe

# Acceptance Criteria
defined page structure and functioning form that allows user to add pinned repository.

# Dependecies
consensus on overview page structure and functionality

# Dev Notes

**Comment by commando954** [comment]
Complete
