### ISSUE TITLE
Create User Profile

### ISSUE THREAD

**Issue by ahammer1** [NSS-Evening-E22/gitsub-hex-clan-e22#15]
# User Story
Create the user profile on the lefthand side.

Include:
Picture
Name
Username
Contact Info

Stretch goals: 

Github activity info
Organizations
Sponsors

# Acceptance Criteria
team agrees on profile styling and information. 
possible team photo? 

# Dependecies

# Dev Notes

**Comment by beileibud** [comment]
Finished the profile build up.
