### ISSUE TITLE
Construct Projects page with components

### ISSUE THREAD

**Issue by scdorr86** [NSS-Evening-E22/gitsub-hex-clan-e22#20]
# User Story
Includes a form that allows a user to add a new project
STRETCH GOALS:
Allow users to search through the projects using the search bar
Allow users to sort using the sort tool in the wireframe

# Acceptance Criteria
form takes in a new project and adds it to dataset and renders to DOM div on page

# Dependecies
form and object structure defined

# Dev Notes

**Comment by SteveCButler** [comment]
complete
